### ISSUE TITLE
State of Audio Control "Loop" not visible 

### ISSUE THREAD

**Issue by DavidJottPunkt** [DarKDinDoN/theme-glass#2]
HEy there, really loving your module as it gieves the standard UI a neat upgrade. One issue though. I am aware that this module makes many things transparent but in the case of the audio control "loop" you loose the capability of seeing the state of this switch. You can't see wether if a track is set to loop or not as it always shows as deactivated.

**Comment by mech-tools** [comment]
Hi,

This should be fixed with: [1.6.0](https://github.com/DarKDinDoN/theme-glass/releases/tag/1.6.0)
