### ISSUE TITLE
[Request] Fully opaque item pages option

### ISSUE THREAD

**Issue by SLinxTheFox** [DarKDinDoN/theme-glass#4]
The item pages are very slightly transparent. This slightly changes the color of any pictures i have in stuff like features for race pages and such depending on the scene that's open.

Is there any way there could be an option for fully opaque item pages aswell as anything similar like journals?

**Comment by mech-tools** [comment]
Implemented with: [1.6.1](https://github.com/DarKDinDoN/theme-glass/releases/tag/1.6.1)

**Comment by SLinxTheFox** [comment]
Thank you so much for both!
