### ISSUE TITLE
[Feature Request] Add theme support for PF2E HUD module

### ISSUE THREAD

**Issue by PlasticMohawk** [DarKDinDoN/theme-glass#6]
Here is the module:

https://github.com/reonZ/pf2e-hud

Presently, this is how it looks:

![image](https://github.com/user-attachments/assets/ee64ab03-c646-4aad-a706-bc51427f557f)

I believe this CSS should help:

body.addBlur #interface #ui-left #pf2e-hud-persistent .app,
body.addBlur #interface #ui-left #pf2e-hud-persistent #hotbar #macro-list,
body.addBlur #interface #ui-left #pf2e-hud-persistent #hotbar #hotbar-page-controls
{
    -webkit-backdrop-filter: blur(5px);
    backdrop-filter: blur(5px);
    background-color: transparent;
}

#interface #ui-left #pf2e-hud-persistent .app,
#interface #ui-left #pf2e-hud-persistent #hotbar #macro-list,
#interface #ui-left #pf2e-hud-persistent #hotbar #hotbar-page-controls {
	background: none;
    background-color: rgba(0,0,0,.05);
    border: 1px solid transparent;
    box-shadow: 0 2px 8px rgba(0,0,0,.75);
    color: rgb(var(--color-text));
    cursor: pointer;
    position: relative;
    text-shadow: 0 0 4px rgba(0,0,0,.75);
}

**Comment by mech-tools** [comment]
Hi,

Added support for this module.
Since there is a lot going on with this module, I won't skin everything but what is immediately visible to users (main interface).

You can find it here: [1.9.0](https://github.com/DarKDinDoN/theme-glass/releases/tag/1.9.0)

**Comment by PlasticMohawk** [comment]
Thanks! Would you mind if I sent additional CSS to add to this when I have it?

**Comment by mech-tools** [comment]
> Thanks! Would you mind if I sent additional CSS to add to this when I have it?

As long as you submit a PR, I don't mind.

Note that I use mixins to avoid excessive code duplication. You'll need to use this so I can merge:
- color: https://github.com/DarKDinDoN/theme-glass/blob/main/styles/features/color-theme.css
- other variables: https://github.com/DarKDinDoN/theme-glass/blob/main/styles/internal/base.css
- components: https://github.com/DarKDinDoN/theme-glass/blob/main/styles/internal/components.css
- fields: https://github.com/DarKDinDoN/theme-glass/blob/main/styles/internal/fields.css

Please use these so I can merge. All of it, but especially colors & variables, so the users can change the colors through settings.

Here is the file you'll need to modify. This is the file where magic happens for this module: https://github.com/DarKDinDoN/theme-glass/blob/main/styles/modules/pf2e-hud.css

As for installation:
- fork
- clone
- npm i
- npm run gulp (have "hot reload" enabled within foundry general settings to avoid unnecessary reloads)
- changes
- commit
- PR

**Comment by PlasticMohawk** [comment]
Thanks! This setup is way over my level CSS-fu however, so i'll need to digest this a bit. I know I will want to add these two selectors but I'll need to educate myself on how to do it according to your specs.

#pf2e-hud-token #pf2e-hud-token-main .joined,
#pf2e-hud-token #pf2e-hud-token-main.exploded .panel

Thanks for the help and additional information!

**Comment by mech-tools** [comment]
Plans got cancelled tonight + token hud is no biggie (mostly the same as persistant interface).

So here it is: [1.9.1](https://github.com/DarKDinDoN/theme-glass/releases/tag/1.9.1)

**Comment by PlasticMohawk** [comment]
This is awesome, thanks! I'll take a look at 1.9 vs. 1.9.1 and see what I can learn from this.
